import {useCallback,useEffect,useRef,useState} from 'react';
import axios from 'axios';
import type {AppSnapshot,AppUser} from '@aapoorti-b2b/domain';
import {api,formatDateTimeIst} from '../../app/shared';
import {Panel} from '../../components/ui';
type Report={kind:string;reason:string;lines:Array<{id:string;quantity:number;reason:string}>};
type Photo={id:string;stage:string;lineId:string|null;createdBy:string;createdAt:string};
type Receipt={lines:Array<{id:string;good:number;damaged:number}>;note:string;resolveMissing:boolean};
type Upload=(id:string,stage:string,lineId:string|null,file:File)=>Promise<void>;
export type Case={photos:Photo[];canReceive:boolean;handover_at?:string;warehouse_received_at?:string;receipt_json?:Receipt;id:string;task_id:string;order_id:string;retailer_name:string;seller_name:string;agent_username:string;status:string;revision:number;report_json:Report;original_json:Array<{id:string;product_sku:string;product_name:string;quantity:number}>;bill_adjusted_at?:string;adjusted_total?:number;paid_amount:number;amount_due?:number;credit_amount:number;proposed_bill:{total:number;lines:Array<{id:string;quantity:number}>};decision_note:string;retry_at?:string;canEdit:boolean;canDecide:boolean;failed_notifications:number;events:Array<{id:number;action:string;actor:string;note:string;created_at:string}>};
type Act=(id:string,action:string,body:Record<string,unknown>)=>Promise<void>;
function EvidencePreview({item,photo,sessionToken}:{item:Case;photo:Photo;sessionToken:string}){
 const [url,setUrl]=useState('');const [error,setError]=useState('');
 useEffect(()=>{const controller=new AbortController();let objectUrl='';void api.get(`/delivery-exceptions/${encodeURIComponent(item.id)}/photos/${encodeURIComponent(photo.id)}`,{headers:{authorization:`Bearer ${sessionToken}`},responseType:'blob',signal:controller.signal}).then(({data})=>{if(!controller.signal.aborted){objectUrl=URL.createObjectURL(data);setUrl(objectUrl);}}).catch(()=>{if(!controller.signal.aborted)setError('Unable to load photo.');});return()=>{controller.abort();if(objectUrl)URL.revokeObjectURL(objectUrl);};},[item.id,photo.id,sessionToken]);
 return <figure>{url?<a href={url} target="_blank" rel="noreferrer"><img src={url} alt={`${photo.stage}: ${item.original_json.find(l=>l.id===photo.lineId)?.product_name||'Visit / handover'}`} style={{maxWidth:'100%',maxHeight:240}}/></a>:<p>{error||'Loading photo...'}</p>}<figcaption>{photo.stage} / {item.original_json.find(l=>l.id===photo.lineId)?.product_name||'Visit / handover'} / {photo.createdBy} / {formatDateTimeIst(photo.createdAt)}</figcaption></figure>;
}
function EvidenceInput({item,stage,lineId,busy,upload}:{item:Case;stage:string;lineId:string|null;busy:boolean;upload:Upload}){
 const label=lineId?item.original_json.find(l=>l.id===lineId)?.product_name:'Visit / handover';
 return <label>{stage}: {label}<input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(item.id,stage,lineId,file);e.target.value='';}}/><small>{(item.photos||[]).filter(p=>p.stage===stage&&p.lineId===lineId).length} photo(s) saved. Photograph damage clearly. Maximum 8 MB.</small></label>;
}
function WarehouseReceipt({item,busy,act,upload}:{item:Case;busy:boolean;act:Act;upload:Upload}){
 const [editing,setEditing]=useState(!item.receipt_json);const [counts,setCounts]=useState<Record<string,{good:string;damaged:string}>>(()=>Object.fromEntries(item.report_json.lines.map(l=>{const saved=item.receipt_json?.lines.find(r=>r.id===l.id);return [l.id,{good:saved?String(saved.good):'',damaged:saved?String(saved.damaged):''}];})));
 const [note,setNote]=useState(item.receipt_json?.note||'');const [resolveMissing,setResolveMissing]=useState(item.receipt_json?.resolveMissing||false);
 const photosReady=item.report_json.lines.every(l=>(item.photos||[]).some(p=>p.stage==='Warehouse receipt'&&p.lineId===l.id));
 return <section><h4>Warehouse Manager receipt and final decision</h4><p>Count the physical goods. Sellable stock becomes available; damaged stock stays blocked. Missing units require an explicit decision and receive no stock credit.</p>
 {editing?<form className="form-grid" onSubmit={e=>{e.preventDefault();void act(item.id,'save-receipt',{revision:item.revision,receipt:{lines:item.report_json.lines.map(l=>({id:l.id,good:Number(counts[l.id].good),damaged:Number(counts[l.id].damaged)})),note,resolveMissing}});}}>
 {item.report_json.lines.map(l=><fieldset className="wide-field" key={l.id}><legend>{item.original_json.find(o=>o.id===l.id)?.product_name} / Expected return: {l.quantity}</legend><div className="form-grid">{(['good','damaged'] as const).map(key=><label key={key}>{key==='good'?'Sellable quantity':'Damaged quantity'}<input required type="number" min="0" max={l.quantity} step="any" value={counts[l.id][key]} onChange={e=>setCounts(c=>({...c,[l.id]:{...c[l.id],[key]:e.target.value}}))}/></label>)}</div></fieldset>)}
 <label className="wide-field">Findings / final decision for any missing quantity<textarea required value={note} onChange={e=>setNote(e.target.value)}/></label><label className="wide-field"><input type="checkbox" checked={resolveMissing} onChange={e=>setResolveMissing(e.target.checked)}/> I have resolved any missing quantity and recorded my final decision above.</label><button className="primary-button" disabled={busy}>Save count and review</button></form>:<><div className="table-wrap"><table><thead><tr><th>Product</th><th>Expected</th><th>Sellable</th><th>Damaged</th><th>Missing</th></tr></thead><tbody>{item.receipt_json?.lines.map(l=><tr key={l.id}><td>{item.original_json.find(o=>o.id===l.id)?.product_name}</td><td>{item.report_json.lines.find(r=>r.id===l.id)?.quantity}</td><td>{l.good}</td><td>{l.damaged}</td><td>{Number(item.report_json.lines.find(r=>r.id===l.id)?.quantity)-l.good-l.damaged}</td></tr>)}</tbody></table></div><p>{item.receipt_json?.note}</p><button className="ghost-button" disabled={busy} onClick={()=>setEditing(true)}>Edit warehouse count</button></>}
 <div className="form-grid">{item.report_json.lines.map(l=><EvidenceInput key={l.id} item={item} stage="Warehouse receipt" lineId={l.id} busy={busy} upload={upload}/>)}</div>
 {!editing?<button className="primary-button" disabled={busy||!photosReady} onClick={()=>void act(item.id,'receive',{revision:item.revision})}>Confirm receipt and update stock</button>:null}{!photosReady?<p>Receiving / condition photos are required for every returned product.</p>:null}</section>;
}
function ExceptionCard({item,busy,act,upload,sessionToken}:{item:Case;busy:boolean;act:Act;upload:Upload;sessionToken:string}){
 const [editing,setEditing]=useState(false);const [kind,setKind]=useState(item.report_json.kind);const [reason,setReason]=useState(item.report_json.reason);const [counts,setCounts]=useState<Record<string,string>>(()=>Object.fromEntries(item.report_json.lines.map(l=>[l.id,String(l.quantity)])));const [reasons,setReasons]=useState<Record<string,string>>(()=>Object.fromEntries(item.report_json.lines.map(l=>[l.id,l.reason])));const [decision,setDecision]=useState('Return');const [note,setNote]=useState('');const [due,setDue]=useState('');const [mode,setMode]=useState('Cash');const [utr,setUtr]=useState('');const [paymentRef]=useState(()=>`DEX-${crypto.randomUUID()}`);
 const [showPhotos,setShowPhotos]=useState(false);
 const reportPhotosReady=item.report_json.kind==='Shop closed'?(item.photos||[]).some(p=>p.stage==='Agent report'):item.report_json.lines.every(l=>(item.photos||[]).some(p=>p.stage==='Agent report'&&p.lineId===l.id));
 const editable=item.canEdit&&['Draft','Correction Requested'].includes(item.status);
 return <article className="panel shortage-card">
  <div className="section-heading"><div><span className="eyebrow">{item.order_id}</span><h3>{item.retailer_name}</h3></div><span className="status-pill pending">{item.status}</span></div>
  <p><strong>{item.report_json.kind}</strong> · Seller: {item.seller_name||'Unassigned'} · Goods custody: {item.warehouse_received_at?'Warehouse received':item.agent_username}</p>
  <div className="table-wrap"><table><thead><tr><th>Product</th><th>Dispatched</th><th>Reported return</th><th>Accepted</th><th>Reason</th></tr></thead><tbody>{item.original_json.map(l=><tr key={l.id}><td>{l.product_name}<small>{l.product_sku}</small></td><td>{l.quantity}</td><td>{item.report_json.lines.find(r=>r.id===l.id)?.quantity||0}</td><td>{item.proposed_bill?.lines.find(r=>r.id===l.id)?.quantity??l.quantity}</td><td>{item.report_json.lines.find(r=>r.id===l.id)?.reason||'—'}</td></tr>)}</tbody></table></div>
  <p>{item.report_json.reason||'Add products and a reason before sending.'}</p><p><strong>{item.bill_adjusted_at?'Revised bill':'Proposed bill'}: Rs.{Number(item.bill_adjusted_at?item.adjusted_total:item.proposed_bill?.total||0).toFixed(2)}</strong> | Already paid: Rs.{Number(item.paid_amount||0).toFixed(2)}</p>{item.bill_adjusted_at?<p><strong>Collect now: Rs.{Number(item.amount_due||0).toFixed(2)}</strong></p>:<p className="helper-text">Confirming the report records the remaining quantities as accepted by the retailer. Collection stays locked until the seller approves the revised bill.</p>}{item.credit_amount>0?<p role="alert">Rs.{Number(item.credit_amount).toFixed(2)} excess payment requires financial review.</p>:null}
  {item.decision_note?<p><strong>Seller decision:</strong> {item.decision_note}</p>:null}{item.retry_at?<p>Retry delivery: {formatDateTimeIst(item.retry_at)}</p>:null}
  {item.status==='Return Authorized'?<p role="status">Return authorized. The agent must hand the listed goods to the warehouse for counting and condition checks. {item.bill_adjusted_at?'The bill is adjusted for accepted goods. Collect the outstanding amount now; returned stock is still with the agent.':'The seller must approve the revised bill before collection unlocks.'}</p>:null}
  {editable?<section><h4>Agent visit / return photo evidence</h4><div className="form-grid">{item.report_json.kind==='Shop closed'?<EvidenceInput item={item} stage="Agent report" lineId={null} busy={busy} upload={upload}/>:item.report_json.lines.map(l=><EvidenceInput key={l.id} item={item} stage="Agent report" lineId={l.id} busy={busy} upload={upload}/>)}</div>{!reportPhotosReady?<p>Save the selected products, then attach a photo for each returned product before sending.</p>:null}</section>:null}
  {item.bill_adjusted_at&&item.canEdit&&!item.warehouse_received_at?<section><h4>Return handover</h4><EvidenceInput item={item} stage="Agent handover" lineId={null} busy={busy} upload={upload}/>{!item.handover_at?<button className="primary-button" disabled={busy||!(item.photos||[]).some(p=>p.stage==='Agent handover')} onClick={()=>void act(item.id,'handover',{revision:item.revision})}>Confirm goods presented to warehouse</button>:<p>Awaiting Warehouse Manager count and receipt. Custody stays with the agent until receipt is confirmed.</p>}</section>:null}
  {item.canReceive&&item.handover_at&&!item.warehouse_received_at?<WarehouseReceipt item={item} busy={busy} act={act} upload={upload}/>:null}
  {item.warehouse_received_at?<p role="status">Warehouse receipt confirmed on {formatDateTimeIst(item.warehouse_received_at)}. {item.status==='Closed'?'Return case closed.':'Physical return complete; payment verification, collection or excess-payment resolution remains open.'}</p>:null}
  {item.warehouse_received_at&&item.receipt_json?<details><summary>Final warehouse count and decision</summary><ul>{item.receipt_json.lines.map(l=><li key={l.id}>{item.original_json.find(o=>o.id===l.id)?.product_name}: sellable {l.good}, damaged {l.damaged}, missing {Number(item.report_json.lines.find(r=>r.id===l.id)?.quantity)-l.good-l.damaged}</li>)}</ul><p>{item.receipt_json.note}</p></details>:null}
  {(item.photos||[]).length?<details onToggle={e=>setShowPhotos(e.currentTarget.open)}><summary>Photo evidence ({item.photos.length})</summary>{showPhotos?item.photos.map(photo=><EvidencePreview key={photo.id} item={item} photo={photo} sessionToken={sessionToken}/>):null}</details>:null}
  {editable&&!editing?<div className="payment-card-actions"><button className="ghost-button" disabled={busy} onClick={()=>setEditing(true)}>Edit products / quantities</button><button className="primary-button" disabled={busy||!reportPhotosReady||!item.report_json.lines.length||!item.report_json.reason.trim()} onClick={()=>void act(item.id,'submit',{revision:item.revision})}>Confirm and send to seller</button><button className="ghost-button" disabled={busy} onClick={()=>void act(item.id,'withdraw',{revision:item.revision})}>Discard draft</button></div>:null}
  {editable&&editing?<form className="form-grid" onSubmit={e=>{e.preventDefault();void act(item.id,'save',{revision:item.revision,report:{kind,reason,lines:item.original_json.flatMap(l=>{const quantity=kind==='Shop closed'?l.quantity:Number(counts[l.id]||0);return quantity>0?[{id:l.id,quantity,reason:kind==='Shop closed'?'Shop closed':reasons[l.id]||'Customer refused'}]:[];})}});}}>
   <label>Delivery outcome<select value={kind} onChange={e=>setKind(e.target.value)}><option>Shop closed</option><option>Returned</option></select></label>
   <label>Report reason / other details<input required value={reason} onChange={e=>setReason(e.target.value)}/></label>
   {kind==='Returned'?item.original_json.map(l=><div className="form-grid wide-field" key={l.id}><label>{l.product_name} — return quantity<input type="number" min="0" max={l.quantity} step="any" value={counts[l.id]||''} placeholder="0 = not returned" onChange={e=>setCounts(c=>({...c,[l.id]:e.target.value}))}/></label><label>Reason (including other)<input required={Number(counts[l.id]||0)>0} value={reasons[l.id]||''} placeholder="Refused, damaged, wrong item, or other reason" onChange={e=>setReasons(r=>({...r,[l.id]:e.target.value}))}/></label></div>):<p className="wide-field">Every dispatched item stays with the delivery agent when the shop is closed.</p>}
   <button className="primary-button" disabled={busy}>Save and review report</button><button type="button" className="ghost-button" onClick={()=>setEditing(false)}>Back to review</button>
  </form>:null}
  {(item.status==='Awaiting Seller'||(item.status==='Return Authorized'&&!item.bill_adjusted_at))&&item.canDecide?<form className="form-grid" onSubmit={e=>{e.preventDefault();void act(item.id,'decide',{revision:item.revision,decision,note,dueAt:decision==='Retry'?new Date(`${due}:00+05:30`).toISOString():undefined});}}>
   <label>Seller final decision<select value={decision} onChange={e=>setDecision(e.target.value)}><option value="Return">Approve return and adjusted bill</option><option value="Correction">Request agent correction</option>{item.report_json.kind==='Shop closed'?<option value="Retry">Retry delivery</option>:null}</select></label>
   <label>Decision reason<input required value={note} onChange={e=>setNote(e.target.value)}/></label>
   {decision==='Retry'?<label>Next delivery date / time (IST)<input required type="datetime-local" value={due} onChange={e=>setDue(e.target.value)}/></label>:null}
   <button className="primary-button" disabled={busy}>Confirm decision and update bill</button>
  </form>:null}
  {item.bill_adjusted_at&&item.canEdit&&Number(item.amount_due)>0?<form className="form-grid" onSubmit={e=>{e.preventDefault();void act(item.id,'collect',{revision:item.revision,mode,amount:item.amount_due,reference:paymentRef,utr});}}>
   <p className="wide-field"><strong>Collect Rs.{Number(item.amount_due).toFixed(2)} now.</strong> Confirm only after receiving the payment.</p>
   <label>Payment mode<select value={mode} onChange={e=>setMode(e.target.value)}><option>Cash</option><option>UPI</option></select></label>
   {mode==='UPI'?<label>UPI transaction reference<input required value={utr} onChange={e=>setUtr(e.target.value)}/></label>:null}
   <button className="primary-button" disabled={busy}>Confirm adjusted payment received</button>
  </form>:null}
  {item.failed_notifications>0?<p role="alert">{item.failed_notifications} notification(s) failed.{item.canDecide?<button className="ghost-button" disabled={busy} onClick={()=>void act(item.id,'retry',{})}>Retry notifications</button>:null}</p>:null}
  <details><summary>Report history</summary><ul>{item.events.map(e=><li key={e.id}>{e.action} · {e.actor} · {formatDateTimeIst(e.created_at)} — {e.note}</li>)}</ul></details>
 </article>;
}
export function DeliveryExceptionRegister({snapshot,sessionToken,currentUser,onChanged}:{snapshot:AppSnapshot;sessionToken:string;currentUser:AppUser;onChanged?:()=>void}){
 const [items,setItems]=useState<Case[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);const [selected,setSelected]=useState('');const [search,setSearch]=useState('');const seq=useRef(0);const busyRef=useRef(false);
 const errorText=(e:unknown)=>axios.isAxiosError(e)?String(e.response?.data?.message||e.message):e instanceof Error?e.message:'Unable to update report.';
 const refresh=useCallback(async()=>{if(busyRef.current)return;const n=++seq.current;try{const {data}=await api.get<{cases:Case[]}>('/delivery-exceptions',{headers:{authorization:`Bearer ${sessionToken}`}});if(n===seq.current){setItems(data.cases);setError('');}}catch(e){if(n===seq.current)setError(errorText(e));}finally{if(n===seq.current)setLoading(false);}},[sessionToken]);
 useEffect(()=>{void refresh();const timer=window.setInterval(()=>void refresh(),3000);return()=>{clearInterval(timer);seq.current++;};},[refresh]);
 const act:Act=async(id,action,body)=>{if(busyRef.current)return;busyRef.current=true;setBusy(true);seq.current++;try{const {data}=await api.post<{cases:Case[]}>(`/delivery-exceptions/${encodeURIComponent(id)}/${action}`,body,{headers:{authorization:`Bearer ${sessionToken}`}});setItems(data.cases);setError('');onChanged?.();}catch(e){setError(errorText(e));}finally{busyRef.current=false;setBusy(false);}};
 const upload:Upload=async(id,stage,lineId,file)=>{if(busyRef.current)return;if(file.size>8*1024*1024){setError('Upload a photo no larger than 8 MB.');return;}busyRef.current=true;setBusy(true);seq.current++;try{const form=new FormData();form.append('photo',file);const {data}=await api.post<{cases:Case[]}>(`/delivery-exceptions/${encodeURIComponent(id)}/photos/${encodeURIComponent(stage)}${lineId?`?lineId=${encodeURIComponent(lineId)}`:''}`,form,{headers:{authorization:`Bearer ${sessionToken}`}});setItems(data.cases);setError('');}catch(e){setError(errorText(e));}finally{busyRef.current=false;setBusy(false);}};
 const roles=[currentUser.role,...currentUser.roles];const canReport=roles.some(r=>['Admin','Delivery','Out Delivery'].includes(r));
 const stops=canReport?snapshot.deliveryTasks.filter(t=>t.side==='Sales'&&t.status==='Handed Over'&&(roles.includes('Admin')||t.assignedTo.toLowerCase()===currentUser.username.toLowerCase())).flatMap(t=>t.routeStops.filter(s=>!s.delivered&&!s.picked).map(s=>({key:`${t.id}|${s.orderId}`,taskId:t.id,orderId:s.orderId,label:`${s.supplierName} / ${s.orderId}`}))):[];
 const start=(kind:string)=>{const stop=stops.find(s=>s.key===selected);if(stop)void act(stop.taskId,'open',{orderId:stop.orderId,kind});};
 return <div className="shortage-register"><Panel title="Delivery exceptions" eyebrow="Agent report / Seller decision / Goods custody">
  <div className="section-heading"><p>Record shop closure or select the products and quantities returned. Review and edit before sending to the seller.</p><button className="ghost-button" disabled={busy} onClick={()=>void refresh()}>Refresh reports</button></div>
  {error?<p role="alert">{error}</p>:null}{loading?<p role="status">Loading delivery reports…</p>:null}
  {canReport?<div className="form-grid"><label className="wide-field">Assigned delivery stop<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select retailer / order</option>{stops.map(s=><option key={s.key} value={s.key}>{s.label}</option>)}</select></label><button className="ghost-button" disabled={busy||!selected} onClick={()=>start('Shop closed')}>Shop closed</button><button className="ghost-button" disabled={busy||!selected} onClick={()=>start('Returned')}>Returned — select products</button></div>:null}
  <div className="form-grid"><label className="wide-field">Find a report<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Retailer, order or status"/></label></div>
  {!loading&&!items.length&&!error?<p>No delivery exceptions.</p>:null}
  <div className="stacked-sections">{items.filter(r=>`${r.retailer_name} ${r.order_id} ${r.status}`.toLowerCase().includes(search.toLowerCase())).map(item=><ExceptionCard key={`${item.id}:${item.revision}`} item={item} busy={busy} act={act} upload={upload} sessionToken={sessionToken}/>)}</div>
 </Panel></div>;
}
