import assert from 'node:assert/strict';
import test from 'node:test';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import pg from 'pg';
import dotenv from 'dotenv';
import ts from 'typescript';
import sharp from 'sharp';
import {prepareDeliveryExceptionPayment,syncDeliveryExceptionPayment} from '../src/delivery-exception-billing.js';
import {randomUUID} from 'node:crypto';
import {createDeliveryExceptionService,assertDeliveryExceptionUpdate} from '../src/delivery-exceptions.js';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../..');
test('delivery exception transactions and WhatsApp flow on isolated PostgreSQL',{skip:process.env.SHORTAGE_TEST_LOCAL!=='1'},async t=>{
 const env=dotenv.parse(fs.readFileSync(path.join(root,'.env')));const config={host:'127.0.0.1',port:5432,user:env.POSTGRES_USER||'aapoorti_app',password:env.POSTGRES_PASSWORD||'aapoorti123',database:env.POSTGRES_DB||'aapoorti_b2b'};
 const setup=new pg.Client(config);await setup.connect();const schema=`delivery_exception_test_${Date.now()}`;await setup.query(`CREATE SCHEMA ${schema}`);const pool=new pg.Pool({...config,options:`-c search_path=${schema}`});
 const deps={query:(sql:string,args?:unknown[])=>pool.query(sql,args),transaction:async<T>(run:(db:pg.PoolClient)=>Promise<T>)=>{const db=await pool.connect();try{await db.query('BEGIN');const result=await run(db);await db.query('COMMIT');return result;}catch(e){await db.query('ROLLBACK');throw e;}finally{db.release();}}};const svc=createDeliveryExceptionService(deps);
 const driver={id:2,username:'driver',fullName:'Driver',role:'Out Delivery',roles:['Out Delivery']};const sales={id:1,username:'sales',fullName:'Seller',role:'Sales',roles:['Sales']};
 try{
  await pool.query(fs.readFileSync(path.join(root,'postgres/init/001-schema.sql'),'utf8'));
  await pool.query(`ALTER TABLE delivery_tasks ADD COLUMN route_json JSONB NOT NULL DEFAULT '[]';INSERT INTO users(id,username,full_name,role,password) VALUES(1,'sales','Seller','Sales','unused'),(2,'driver','Driver','Out Delivery','unused'),(3,'warehouse','Warehouse Manager','Warehouse Manager','unused');INSERT INTO counterparties(id,type,name,created_by) VALUES('SHOP','Shop','Test shop','test');INSERT INTO products(sku,name,category,unit,default_weight_kg,tolerance_kg,tolerance_percent,allowed_warehouse_ids_json,slabs_json,created_by) VALUES('SOAP','Soap','Test','Piece',1,0,0,'["WH"]','[]','test');`);
  let n=0;async function trip(){const id=`TASK-${++n}`,order=`SO-${n}`;await pool.query("INSERT INTO sales_orders(id,cart_id,shop_id,product_sku,salesman_id,warehouse_id,quantity,rate,taxable_amount,total_amount,payment_mode,delivery_mode,status) VALUES($1,$2,'SHOP','SOAP',1,'WH',10,20,200,200,'Cash','Delivery','Out for Delivery')",[order+'-L',order]);const stops=[{orderId:order,supplierId:'SHOP',supplierName:'Test shop',warehouseId:'WH',delivered:false,picked:false,paid:false},{orderId:'OTHER',delivered:false,picked:false}];await pool.query("INSERT INTO delivery_tasks(id,side,linked_order_id,mode,source_location,destination_location,assigned_to,status,route_json) VALUES($1,'Sales',$2,'Delivery','WH','Shop','driver','Handed Over',$3::jsonb)",[id,order,JSON.stringify(stops)]);return {id,order,stops};}

  const dbSource=ts.createSourceFile('db.ts',fs.readFileSync(path.join(root,'apps/api/src/db.ts'),'utf8'),ts.ScriptTarget.Latest,true);
  const dbCode=ts.transpileModule(dbSource.statements.filter(node=>ts.isFunctionDeclaration(node)&&['createPayment','createSalesReturn','recalculateLedger','upsertLedger'].includes(node.name?.text||'')).map(node=>node.getText(dbSource).replace(/^export /,'')).join('\n'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}}).outputText;
  const paymentDeps={ready:Promise.resolve(),withTransaction:deps.transaction,query:(sql:string,args:unknown[],client:any)=>(client||pool).query(sql,args),one:async(sql:string,args:unknown[],client:any)=>(await (client||pool).query(sql,args)).rows[0],operationalDate:()=>new Date().toISOString(),now:()=>new Date().toISOString(),isoValue:(v:any)=>v?new Date(v).toISOString():'',numberValue:(v:any)=>Number(v||0),stringValue:(v:any)=>String(v??''),makeId:(p:string)=>`${p}-${randomUUID()}`,getSnapshot:async()=>({}),invalidateSnapshotCacheForSql:()=>{},prepareDeliveryExceptionPayment,syncDeliveryExceptionPayment};
  const pay=new Function(...Object.keys(paymentDeps),dbCode+';return createPayment;')(...Object.values(paymentDeps));
  const genericReturn=new Function(...Object.keys(paymentDeps),dbCode+';return createSalesReturn;')(...Object.values(paymentDeps));
  const payment=(order:string,amount:number,reference:string)=>({side:'Sales',linkedOrderId:order,amount,mode:'Cash',referenceNumber:reference,verificationStatus:'Submitted'});
  const evidence=await sharp({create:{width:16,height:16,channels:3,background:'#336699'}}).jpeg().toBuffer();
  const warehouse={id:3,username:'warehouse',fullName:'Warehouse Manager',role:'Warehouse Manager',roles:['Warehouse Manager'],warehouseIds:['WH']};
  async function attachReport(r:any){for(const line of r.report_json.kind==='Shop closed'?[{id:null}]:r.report_json.lines)await svc.addPhoto(r.id,'Agent report',line.id,evidence,driver);}
  async function submitPhotographed(id:string,v:number,actor=driver){const r=await svc.get(id,actor);if(['Draft','Correction Requested'].includes(r.status))await attachReport(r);return svc.submit(id,v,actor);}
  async function returned(f:any,quantity=3){let r=await svc.open(f.id,f.order,'Returned',driver);r=await svc.save(r.id,{kind:'Returned',reason:'Customer returns listed goods; accepts the rest',lines:[{id:f.order+'-L',quantity,reason:'Refused'}]},r.revision,driver);return submitPhotographed(r.id,r.revision,driver);}
  await t.test('seller approval adjusts seven accepted units immediately, unlocks collection, and duplicate approval is harmless',async()=>{
   const f=await trip();const r=await returned(f);await assert.rejects(()=>pay(payment(f.order,200,'EARLY'),driver),/hold/);
   const input={decision:'Return',note:'Approve 7 accepted and 3 returned',revision:r.revision};const [a,b]=await Promise.all([svc.decide(r.id,input,sales),svc.decide(r.id,input,sales)]);assert.equal(a.adjusted_total,140);assert.equal(b.adjusted_total,140);
   assert.equal((await pool.query('SELECT quantity FROM sales_orders WHERE id=$1',[f.order+'-L'])).rows[0].quantity,7);
   const task=(await pool.query('SELECT * FROM delivery_tasks WHERE id=$1',[f.id])).rows[0];assert.equal(task.route_json[0].amountToPay,140);assert.equal(task.route_json[0].delivered,true);
   await assert.rejects(()=>pay(payment(f.order,200,'OLD-BILL'),driver),/adjusted outstanding/);await assert.rejects(()=>pay(payment(f.order,140,'WRONG-AGENT'),{...driver,username:'other'}),/assigned/);
   await Promise.all([pay(payment(f.order,140,'PAID-ONCE'),driver),pay(payment(f.order,140,'PAID-ONCE'),driver)]);
   assert.equal((await pool.query("SELECT count(*)::int AS n FROM payments WHERE linked_order_id=$1",[f.order])).rows[0].n,1);assert.equal((await svc.get(r.id,driver)).amount_due,0);
   const paidTask=(await pool.query('SELECT * FROM delivery_tasks WHERE id=$1',[f.id])).rows[0];assert.equal(paidTask.route_json[0].paid,true);assert.equal(paidTask.route_json[0].collectionAmount,140);assert.equal((await pool.query('SELECT pending_amount FROM ledger_entries WHERE linked_order_id=$1',[f.order])).rows[0].pending_amount,0);
   const update={status:'Delivered',assignedTo:'driver',routeStops:structuredClone(paidTask.route_json)};await assertDeliveryExceptionUpdate(pool as any,paidTask,update);assert.equal(update.status,'Handed Over');assert.equal((await svc.get(r.id,driver)).status,'Return Authorized');
   assert.equal((await pool.query('SELECT count(*)::int AS n FROM inventory_lots')).rows[0].n,0);
  });
  await t.test('discounts, GST, delivery charge and advance reconcile before collecting only the remaining balance',async()=>{
   const f=await trip();await pool.query('UPDATE sales_orders SET cd_tod_rate=18,cd_amount=20,taxable_amount=200,gst_rate=18,gst_amount=36,total_amount=216,delivery_charge=10 WHERE cart_id=$1',[f.order]);await pay(payment(f.order,50,'ADVANCE'),sales);const r=await returned(f);
   await svc.decide(r.id,{decision:'Return',note:'Approved adjusted invoice',revision:r.revision},sales);const view=await svc.get(r.id,driver);assert.equal(view.adjusted_total,161.2);assert.equal(view.amount_due,111.2);assert.equal(view.paid_amount,50);
   await pay(payment(f.order,111.2,'BALANCE'),driver);assert.equal((await svc.get(r.id,driver)).amount_due,0);
  });
  await t.test('all goods returned yields no collection and prepaid excess remains financial review without restoring stock',async()=>{
   const f=await trip();await pay(payment(f.order,100,'FULL-RETURN-ADVANCE'),sales);const r=await returned(f,10);await svc.decide(r.id,{decision:'Return',note:'All goods refused',revision:r.revision},sales);const view=await svc.get(r.id,driver);assert.equal(view.adjusted_total,0);assert.equal(view.amount_due,0);assert.equal(view.credit_amount,100);assert.equal((await pool.query('SELECT status FROM sales_orders WHERE cart_id=$1',[f.order])).rows[0].status,'Cancelled');await assert.rejects(()=>pay(payment(f.order,1,'EXTRA'),driver),/adjusted outstanding/);
  });
  await t.test('concurrent different payment references cannot overcollect and stale route totals cannot overwrite approved bill',async()=>{
   const f=await trip();const r=await returned(f);await svc.decide(r.id,{decision:'Return',note:'Approve',revision:r.revision},sales);
   const results=await Promise.allSettled([pay(payment(f.order,140,'CONCURRENT-A'),driver),pay(payment(f.order,140,'CONCURRENT-B'),driver)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);const task=(await pool.query('SELECT * FROM delivery_tasks WHERE id=$1',[f.id])).rows[0];const payload={status:'Handed Over',assignedTo:'driver',routeStops:structuredClone(task.route_json)};payload.routeStops[0].amountToPay=200;await assert.rejects(()=>assertDeliveryExceptionUpdate(pool as any,task,payload),/adjusted delivery stop/);
  });
  await t.test('agent scope, draft persistence, quantity bounds and no stock or bill mutation',async()=>{const f=await trip();await assert.rejects(()=>svc.open(f.id,f.order,'Returned',{...driver,username:'other'}),/assigned/);const r=await svc.open(f.id,f.order,'Returned',driver);assert.equal((await svc.open(f.id,f.order,'Returned',driver)).id,r.id);await assert.rejects(()=>svc.submit(r.id,r.revision,driver),/products/);await assert.rejects(()=>svc.save(r.id,{kind:'Returned',reason:'Refused',lines:[{id:f.order+'-L',quantity:11,reason:'Refused'}]},r.revision,driver),/quantity/);const saved=await svc.save(r.id,{kind:'Returned',reason:'Wrong pack',lines:[{id:f.order+'-L',quantity:3,reason:'Wrong pack'}]},r.revision,driver);assert.equal((await svc.get(r.id,driver)).report_json.lines[0].quantity,3);assert.equal((await pool.query('SELECT total_amount FROM sales_orders WHERE id=$1',[f.order+'-L'])).rows[0].total_amount,200);assert.equal((await pool.query('SELECT count(*)::int AS n FROM inventory_lots')).rows[0].n,0);await assert.rejects(()=>svc.save(r.id,saved.report_json,r.revision,driver),/changed/);});
  await t.test('confirmation is idempotent and only seller can decide; corrections reopen editing',async()=>{const f=await trip();const r=await svc.open(f.id,f.order,'Shop closed',driver);const submitted=await submitPhotographed(r.id,r.revision,driver);assert.equal((await submitPhotographed(r.id,r.revision,driver)).revision,submitted.revision);await assert.rejects(()=>svc.save(r.id,r.report_json,submitted.revision,driver),/locked/);const input={decision:'Correction',note:'Please check with the customer',revision:submitted.revision};await assert.rejects(()=>svc.decide(r.id,input,driver),/seller/);await assert.rejects(()=>svc.decide(r.id,input,{...sales,id:99}),/seller/);const correction=await svc.decide(r.id,input,sales);assert.equal(correction.status,'Correction Requested');const changed=await svc.save(r.id,{...r.report_json,reason:'Customer confirms shop closed today'},correction.revision,driver);assert.equal(changed.report_json.reason,'Customer confirms shop closed today');await assert.rejects(()=>svc.submit(r.id,submitted.revision,driver),/changed/);});
  await t.test('exception stop cannot be completed, removed or reassigned while other stops can progress',async()=>{const f=await trip();await svc.open(f.id,f.order,'Shop closed',driver);const task=(await pool.query('SELECT * FROM delivery_tasks WHERE id=$1',[f.id])).rows[0];const payload={status:'Handed Over',assignedTo:'driver',routeStops:task.route_json};await assert.rejects(()=>assertDeliveryExceptionUpdate(pool as any,task,{...payload,status:'Delivered'}),/exceptions/);await assert.rejects(()=>assertDeliveryExceptionUpdate(pool as any,task,{...payload,routeStops:[]}),/exception/);await assert.rejects(()=>assertDeliveryExceptionUpdate(pool as any,task,{...payload,assignedTo:'someone'}),/exceptions/);await assertDeliveryExceptionUpdate(pool as any,task,{...payload,routeStops:task.route_json.map((s:any)=>s.orderId==='OTHER'?{...s,delivered:true}:s)});});
  await t.test('seller retry requires a future date; authorized return keeps custody and stock unchanged',async()=>{const f=await trip();let r=await svc.open(f.id,f.order,'Shop closed',driver);r=await submitPhotographed(r.id,r.revision,driver);await assert.rejects(()=>svc.decide(r.id,{decision:'Retry',note:'Visit later',revision:r.revision,dueAt:'2000-01-01'},sales),/future/);const retry=await svc.decide(r.id,{decision:'Retry',note:'Visit tomorrow',revision:r.revision,dueAt:new Date(Date.now()+86400000).toISOString()},sales);assert.equal(retry.status,'Retry Scheduled');const second=await svc.open(f.id,f.order,'Shop closed',driver);assert.notEqual(second.id,r.id);const sent=await submitPhotographed(second.id,second.revision,driver);const approved=await svc.decide(second.id,{decision:'Return',note:'Bring all goods back',revision:sent.revision},sales);assert.equal(approved.status,'Return Authorized');assert.equal(approved.agent_username,'driver');assert.equal((await pool.query('SELECT count(*)::int AS n FROM inventory_lots')).rows[0].n,0);});
  await t.test('old unresolved reports stay visible, unauthorized roles are denied, failed alerts retry',async()=>{const f=await trip();const r=await svc.open(f.id,f.order,'Shop closed',driver);await submitPhotographed(r.id,r.revision,driver);await pool.query("UPDATE delivery_exceptions SET created_at=NOW()-INTERVAL '100 days' WHERE id=$1",[r.id]);await pool.query("UPDATE delivery_exception_notifications SET status='Failed' WHERE case_id=$1",[r.id]);assert.ok((await svc.list(sales)).cases.some(c=>c.id===r.id&&c.failed_notifications>0));assert.equal((await svc.list({...driver,username:'other'})).cases.length,0);await assert.rejects(()=>svc.list({...sales,role:'Purchaser',roles:['Purchaser']}),/access/);await svc.retryNotifications(r.id,sales);assert.equal((await svc.get(r.id,sales)).failed_notifications,0);});

  await t.test('approval outbox immediately offers the assigned agent Collect payment with the adjusted balance',async()=>{
   await pool.query("UPDATE delivery_exception_notifications SET status='Sent'");await pool.query("UPDATE users SET mobile_number=CASE WHEN id=1 THEN '919999999991' ELSE '919999999992' END WHERE id IN (1,2)");const f=await trip();const r=await returned(f);await svc.decide(r.id,{decision:'Return',note:'Approve on site',revision:r.revision},sales);
   const source=ts.createSourceFile('integration.ts',fs.readFileSync(path.join(root,'apps/api/src/whatsapp-integration.ts'),'utf8'),ts.ScriptTarget.Latest,true);const code=ts.transpileModule(source.statements.filter(s=>ts.isFunctionDeclaration(s)&&s.name?.text==='processDeliveryExceptions').map(s=>s.getText(source).replace(/^export /,'')).join('\n'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}}).outputText;
   const sent:any[]=[];const deps={executeDatabaseQuery:(sql:string,args:any[])=>pool.query(sql,args),whatsappAdminUsernames:()=>new Set(),compact:(s:string,n:number)=>s.slice(0,n),sendButtons:async(phone:string,body:string,buttons:any[])=>sent.push({phone,body,buttons})};const run=new Function(...Object.keys(deps),'let deliveryExceptionSweep=false;'+code+';return processDeliveryExceptions;')(...Object.values(deps));await run();assert.ok(sent.some(m=>m.phone==='919999999992'&&m.body.includes('Collect now: Rs.140.00')&&m.buttons.some((b:any)=>b.title==='Collect payment')));assert.equal(sent.length,2);await run();assert.equal(sent.length,2);
  });
  await t.test('warehouse register excludes non-WhatsApp orders and other warehouse scopes',async()=>{
   const f=await trip();const r=await svc.open(f.id,f.order,'Shop closed',driver);const warehouse={id:3,username:'warehouse',fullName:'Warehouse',role:'Warehouse Manager',roles:['Warehouse Manager'],warehouseIds:['WH']};assert.equal((await svc.list(warehouse)).cases.length,0);
   await pool.query("UPDATE delivery_exceptions SET original_json=jsonb_set(original_json,'{0,note}','\"WhatsApp confirmed order WAD-TEST\"') WHERE id=$1",[r.id]);assert.ok((await svc.list(warehouse)).cases.some(c=>c.id===r.id));assert.equal((await svc.list({...warehouse,warehouseIds:['OTHER']})).cases.length,0);
  });
  await t.test('WhatsApp product selection, quantity entry, edit, submit and seller confirmation share persisted reports',async()=>{
   const f=await trip();const source=ts.createSourceFile('integration.ts',fs.readFileSync(path.join(root,'apps/api/src/whatsapp-integration.ts'),'utf8'),ts.ScriptTarget.Latest,true);const code=ts.transpileModule(source.statements.filter(s=>ts.isFunctionDeclaration(s)&&['handleDeliveryExceptionMessage','sendDeliveryExceptionCard'].includes(s.name?.text||'')).map(s=>s.getText(source)).join('\n'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}}).outputText;
   const messages:any[]=[];const collectionActions:any[]=[];const dependencies={deliveryExceptionService:svc,executeDatabaseQuery:deps.query,isWhatsAppAdminUser:()=>false,text:(v:any)=>String(v??''),compact:(v:string,n:number)=>v.slice(0,n),getSnapshot:async()=>({deliveryTasks:[{id:f.id,assignedTo:'driver',routeStops:(await pool.query('SELECT route_json FROM delivery_tasks WHERE id=$1',[f.id])).rows[0].route_json}]}),handleStaffWhatsAppMessage:async(message:any)=>{collectionActions.push(message.interactive.button_reply.id);return true;},deliveryTaskAllowed:()=>true,sendText:async(_p:any,body:any)=>messages.push({body}),sendButtons:async(_p:any,body:any,buttons:any)=>messages.push({body,buttons}),sendGraphMessage:async(_p:any,body:any)=>messages.push({body}),processDeliveryExceptions:async()=>{},downloadReturnPhoto:async()=>evidence};
   const handle=new Function(...Object.keys(dependencies),code+';return handleDeliveryExceptionMessage;')(...Object.values(dependencies));const click=(id:string,actor=driver)=>handle({interactive:{button_reply:{id}}},'919999999999',actor);const say=(body:string,actor=driver)=>handle({text:{body}},'919999999999',actor);
   await click(`wa-ex:new:${f.id}:0:returned`);let r=(await svc.list(driver)).cases.find(c=>c.task_id===f.id);await click(`wa-ex:products:${r.id}:0`);await click(`wa-ex:product:${r.id}:${f.order}-L`);await say('3 | Packaging damaged');r=await svc.get(r.id,driver);assert.equal(r.report_json.lines[0].quantity,3);await click(`wa-ex:photo:${r.id}:report:${f.order}-L`);await handle({id:'PHOTO-WA-1',image:{id:'MEDIA-1'}},'919999999999',driver);await click(`wa-ex:submit:${r.id}:${r.revision}`);r=await svc.get(r.id,sales);assert.equal(r.status,'Awaiting Seller');await click(`wa-ex:decision:${r.id}:${r.revision}:Return`,sales);await say('Return listed goods for warehouse inspection',sales);assert.equal((await svc.get(r.id,sales)).status,'Awaiting Seller');await click(`wa-ex:decide-confirm:${r.id}:${r.revision}`,sales);assert.equal((await svc.get(r.id,sales)).status,'Return Authorized');assert.ok(messages.some(m=>m.buttons?.some((b:any)=>b.title==='Confirm and send')));await click(`wa-ex:view:${r.id}`);assert.ok(messages.some(m=>m.body?.includes?.('Collect now: Rs.140.00')&&m.buttons?.some((b:any)=>b.title==='Collect payment')));await click(`wa-ex:collect:${r.id}`);assert.deepEqual(collectionActions,[`wa-collect:now:${f.id}:0`]);
   await pool.query("UPDATE delivery_exceptions SET original_json=jsonb_set(original_json,'{0,note}','\"WhatsApp confirmed order WAD-TEST\"') WHERE id=$1",[r.id]);
   await click(`wa-ex:photos:${r.id}:handover:0`);await handle({id:'PHOTO-WA-HANDOVER',image:{id:'MEDIA-2'}},'919999999999',driver);r=await svc.get(r.id,driver);await click(`wa-ex:handover:${r.id}:${r.revision}`);
   r=await svc.get(r.id,warehouse);await click(`wa-ex:count:${r.id}:${r.revision}`,warehouse);await say('1=2,1 | One damaged pack placed in quarantine',warehouse);r=await svc.get(r.id,warehouse);assert.equal(r.receipt_json.lines[0].damaged,1);
   await click(`wa-ex:photo:${r.id}:receipt:${f.order}-L`,warehouse);await handle({id:'PHOTO-WA-RECEIPT',image:{id:'MEDIA-3'}},'919999999993',warehouse);await click(`wa-ex:receive:${r.id}:${r.revision}`,warehouse);assert.equal((await svc.get(r.id,warehouse)).status,'Warehouse Received');assert.ok(messages.some(m=>m.buttons?.some((b:any)=>b.title==='Confirm receipt')));

  });

  async function approvedReturn(quantity=3){const f=await trip();await pool.query("UPDATE sales_orders SET note='WhatsApp confirmed order WAD-TEST' WHERE cart_id=$1",[f.order]);let r=await returned(f,quantity);r=await svc.decide(r.id,{decision:'Return',note:'Approved return',revision:r.revision},sales);return {f,r};}
  async function handover(f:any,r:any){await svc.addPhoto(r.id,'Agent handover',null,evidence,driver);return svc.handover(r.id,r.revision,driver);}
  await t.test('agent visit evidence is mandatory, authorized, durable and validated as an actual image',async()=>{
   const f=await trip();const r=await svc.open(f.id,f.order,'Shop closed',driver);await assert.rejects(()=>svc.submit(r.id,r.revision,driver),/photo/);
   await assert.rejects(()=>svc.addPhoto(r.id,'Agent report',null,evidence,{...driver,username:'other'}),/assigned/);
   await assert.rejects(()=>svc.addPhoto(r.id,'Agent report',null,Buffer.from('not an image'),driver));
   const id=await svc.addPhoto(r.id,'Agent report',null,evidence,driver,false,'WhatsApp','UNIQUE-PHOTO');assert.equal(await svc.addPhoto(r.id,'Agent report',null,evidence,driver,false,'WhatsApp','UNIQUE-PHOTO'),id);
   const stored=await svc.photo(r.id,id,sales);assert.equal((await sharp(stored.image_bytes).metadata()).format,'jpeg');const view=await svc.get(r.id,driver);assert.equal(view.photos.length,1);assert.equal(view.photos[0].sha256.length,64);assert.equal(view.photos[0].image_bytes,undefined);assert.equal(view.revision,r.revision);
   await assert.rejects(()=>svc.photo(r.id,id,{...driver,username:'other'}),/unavailable/);await svc.submit(r.id,r.revision,driver);
  });
  await t.test('only scoped Warehouse Manager can receive; handover and receiving photos are compulsory',async()=>{
   const {f,r}=await approvedReturn();await assert.rejects(()=>svc.handover(r.id,r.revision,driver),/photo/);
   const input={lines:[{id:f.order+'-L',good:2,damaged:1}],note:'One damaged pack',resolveMissing:false};
   await assert.rejects(()=>svc.saveReceipt(r.id,input,r.revision,warehouse),/awaiting warehouse/);
   const presented=await handover(f,r);assert.equal(presented.status,'Awaiting Warehouse');
   for(const actor of [sales,driver,{...sales,role:'Admin',roles:['Admin']},{...warehouse,warehouseIds:['OTHER']}])await assert.rejects(()=>svc.saveReceipt(r.id,input,presented.revision,actor),/Warehouse Manager/);
   const counted=await svc.saveReceipt(r.id,input,presented.revision,warehouse);await assert.rejects(()=>svc.finalizeReceipt(r.id,counted.revision,warehouse),/photo/);
  });
  await t.test('receipt restores only sellable stock, blocks damaged stock, changes no bill, and concurrent confirmations are idempotent',async()=>{
   const {f,r}=await approvedReturn();const presented=await handover(f,r);const counted=await svc.saveReceipt(r.id,{lines:[{id:f.order+'-L',good:2,damaged:1}],note:'One broken unit quarantined',resolveMissing:false},presented.revision,warehouse);
   await svc.addPhoto(r.id,'Warehouse receipt',f.order+'-L',evidence,warehouse);
   const [a,b]=await Promise.all([svc.finalizeReceipt(r.id,counted.revision,warehouse),svc.finalizeReceipt(r.id,counted.revision,warehouse)]);assert.equal(a.status,'Warehouse Received');assert.equal(b.revision,a.revision);
   const totals=(await pool.query('SELECT SUM(quantity_available) AS good,SUM(quantity_blocked) AS damaged,count(*)::int AS n FROM inventory_lots WHERE source_order_id=$1',[r.id])).rows[0];assert.equal(totals.good,2);assert.equal(totals.damaged,1);assert.equal(totals.n,2);
   assert.equal((await pool.query('SELECT total_amount FROM sales_orders WHERE cart_id=$1',[f.order])).rows[0].total_amount,140);assert.equal((await pool.query('SELECT count(*)::int AS n FROM sales_returns WHERE return_group_id=$1',[r.id])).rows[0].n,2);
   const task=(await pool.query('SELECT * FROM delivery_tasks WHERE id=$1',[f.id])).rows[0];const update={status:'Delivered',assignedTo:'driver',routeStops:task.route_json};await assertDeliveryExceptionUpdate(pool as any,task,update);assert.equal(update.status,'Delivered');assert.equal(task.route_json[0].returnReceived,true);
   await assert.rejects(()=>svc.finalizeReceipt(r.id,counted.revision+1,warehouse),/already/);await assert.rejects(()=>svc.addPhoto(r.id,'Warehouse receipt',f.order+'-L',evidence,warehouse),/before warehouse receipt/);
   await pay(payment(f.order,140,'POST-RECEIPT'),driver);assert.equal((await svc.get(r.id,warehouse)).status,'Warehouse Received');
   await deps.transaction(async db=>{await db.query("UPDATE payments SET verification_status='Verified' WHERE linked_order_id=$1",[f.order]);await syncDeliveryExceptionPayment(db,(await db.query('SELECT * FROM delivery_exceptions WHERE id=$1',[r.id])).rows[0]);});assert.equal((await svc.get(r.id,warehouse)).status,'Closed');
  });
  await t.test('generic linked return cannot duplicate approved return stock or credit, including line-only references',async()=>{
   const {f}=await approvedReturn();for(const linkedOrderId of [f.order,undefined])await assert.rejects(()=>genericReturn({mode:'Adhoc',linkedOrderId,shopId:'SHOP',warehouseId:'WH',lines:[{linkedOrderLineId:f.order+'-L',productSku:'SOAP',quantity:1,rate:20,reason:'Damage'}]},warehouse),/linked delivery exception warehouse receipt/);
  });
  await t.test('missing quantity requires an explicit manager decision and never restores absent units',async()=>{
   const {f,r}=await approvedReturn();const presented=await handover(f,r);const input={lines:[{id:f.order+'-L',good:1,damaged:1}],note:'One missing unit investigated; manager accepts shortage against agent handover record',resolveMissing:false};
   await assert.rejects(()=>svc.saveReceipt(r.id,input,presented.revision,warehouse),/explicit/);await assert.rejects(()=>svc.saveReceipt(r.id,{...input,lines:[{id:f.order+'-L',good:3,damaged:1}]},presented.revision,warehouse),/exceed/);
   const counted=await svc.saveReceipt(r.id,{...input,resolveMissing:true},presented.revision,warehouse);await svc.addPhoto(r.id,'Warehouse receipt',f.order+'-L',evidence,warehouse);await svc.finalizeReceipt(r.id,counted.revision,warehouse);
   const view=await svc.get(r.id,warehouse);assert.ok(view.events.some((e:any)=>e.action==='Missing return quantity resolved'&&e.note.includes('1 missing')));assert.equal((await pool.query('SELECT SUM(quantity_available+quantity_blocked) AS n FROM inventory_lots WHERE source_order_id=$1',[r.id])).rows[0].n,2);
  });
  await t.test('handover alerts reach the scoped Warehouse Manager and exclude another warehouse',async()=>{
   await pool.query("UPDATE delivery_exception_notifications SET status='Sent'");await pool.query("UPDATE users SET mobile_number='919999999993',warehouse_ids_json='[\"WH\"]' WHERE id=3");await pool.query("INSERT INTO users(id,username,full_name,role,password,mobile_number,warehouse_ids_json) VALUES(4,'otherwarehouse','Other Warehouse','Warehouse Manager','unused','919999999994','[\"OTHER\"]')");
   const {f,r}=await approvedReturn();await handover(f,r);
   const source=ts.createSourceFile('integration.ts',fs.readFileSync(path.join(root,'apps/api/src/whatsapp-integration.ts'),'utf8'),ts.ScriptTarget.Latest,true);const code=ts.transpileModule(source.statements.filter(s=>ts.isFunctionDeclaration(s)&&s.name?.text==='processDeliveryExceptions').map(s=>s.getText(source).replace(/^export /,'')).join('\n'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}}).outputText;
   const sent:any[]=[];const notifyDeps={executeDatabaseQuery:deps.query,whatsappAdminUsernames:()=>new Set(),compact:(s:string,n:number)=>s.slice(0,n),sendButtons:async(phone:string,body:string,buttons:any[])=>sent.push({phone,body,buttons})};const run=new Function(...Object.keys(notifyDeps),'let deliveryExceptionSweep=false;'+code+';return processDeliveryExceptions;')(...Object.values(notifyDeps));await run();assert.ok(sent.some(m=>m.phone==='919999999993'&&m.body.includes('Awaiting Warehouse')));assert.ok(!sent.some(m=>m.phone==='919999999994'));
  });
  await t.test('fully returned unpaid order can close physically and financially, but prepaid excess stays open',async()=>{
   for(const prepaid of [false,true]){const f=await trip();await pool.query("UPDATE sales_orders SET note='WhatsApp confirmed order WAD-TEST' WHERE cart_id=$1",[f.order]);if(prepaid)await pay(payment(f.order,200,'PREPAID-RETURN'),sales);let r=await returned(f,10);r=await svc.decide(r.id,{decision:'Return',note:'All returned',revision:r.revision},sales);r=await handover(f,r);r=await svc.saveReceipt(r.id,{lines:[{id:f.order+'-L',good:10,damaged:0}],note:'All received sellable',resolveMissing:false},r.revision,warehouse);await svc.addPhoto(r.id,'Warehouse receipt',f.order+'-L',evidence,warehouse);r=await svc.finalizeReceipt(r.id,r.revision,warehouse);assert.equal(r.status,prepaid?'Warehouse Received':'Closed');}
  });
 }finally{await pool.end();await setup.query(`DROP SCHEMA ${schema} CASCADE`);await setup.end();}
});
