import assert from 'node:assert/strict';
import test from 'node:test';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import pg from 'pg';
import dotenv from 'dotenv';
import ts from 'typescript';
import {createDeliveryExceptionService,assertDeliveryExceptionUpdate} from '../src/delivery-exceptions.js';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../..');
test('delivery exception transactions and WhatsApp flow on isolated PostgreSQL',{skip:process.env.SHORTAGE_TEST_LOCAL!=='1'},async t=>{
 const env=dotenv.parse(fs.readFileSync(path.join(root,'.env')));const config={host:'127.0.0.1',port:5432,user:env.POSTGRES_USER||'aapoorti_app',password:env.POSTGRES_PASSWORD||'aapoorti123',database:env.POSTGRES_DB||'aapoorti_b2b'};
 const setup=new pg.Client(config);await setup.connect();const schema=`delivery_exception_test_${Date.now()}`;await setup.query(`CREATE SCHEMA ${schema}`);const pool=new pg.Pool({...config,options:`-c search_path=${schema}`});
 const deps={query:(sql:string,args?:unknown[])=>pool.query(sql,args),transaction:async<T>(run:(db:pg.PoolClient)=>Promise<T>)=>{const db=await pool.connect();try{await db.query('BEGIN');const result=await run(db);await db.query('COMMIT');return result;}catch(e){await db.query('ROLLBACK');throw e;}finally{db.release();}}};const svc=createDeliveryExceptionService(deps);
 const driver={id:2,username:'driver',fullName:'Driver',role:'Out Delivery',roles:['Out Delivery']};const sales={id:1,username:'sales',fullName:'Seller',role:'Sales',roles:['Sales']};
 try{
  await pool.query(fs.readFileSync(path.join(root,'postgres/init/001-schema.sql'),'utf8'));
  await pool.query(`ALTER TABLE delivery_tasks ADD COLUMN route_json JSONB NOT NULL DEFAULT '[]';INSERT INTO users(id,username,full_name,role,password) VALUES(1,'sales','Seller','Sales','unused'),(2,'driver','Driver','Out Delivery','unused');INSERT INTO counterparties(id,type,name,created_by) VALUES('SHOP','Shop','Test shop','test');INSERT INTO products(sku,name,category,unit,default_weight_kg,tolerance_kg,tolerance_percent,allowed_warehouse_ids_json,slabs_json,created_by) VALUES('SOAP','Soap','Test','Piece',1,0,0,'["WH"]','[]','test');`);
  let n=0;async function trip(){const id=`TASK-${++n}`,order=`SO-${n}`;await pool.query("INSERT INTO sales_orders(id,cart_id,shop_id,product_sku,salesman_id,warehouse_id,quantity,rate,taxable_amount,total_amount,payment_mode,delivery_mode,status) VALUES($1,$2,'SHOP','SOAP',1,'WH',10,20,200,200,'Cash','Delivery','Out for Delivery')",[order+'-L',order]);const stops=[{orderId:order,supplierId:'SHOP',supplierName:'Test shop',warehouseId:'WH',delivered:false,picked:false,paid:false},{orderId:'OTHER',delivered:false,picked:false}];await pool.query("INSERT INTO delivery_tasks(id,side,linked_order_id,mode,source_location,destination_location,assigned_to,status,route_json) VALUES($1,'Sales',$2,'Delivery','WH','Shop','driver','Handed Over',$3::jsonb)",[id,order,JSON.stringify(stops)]);return {id,order,stops};}
  await t.test('agent scope, draft persistence, quantity bounds and no stock or bill mutation',async()=>{const f=await trip();await assert.rejects(()=>svc.open(f.id,f.order,'Returned',{...driver,username:'other'}),/assigned/);const r=await svc.open(f.id,f.order,'Returned',driver);assert.equal((await svc.open(f.id,f.order,'Returned',driver)).id,r.id);await assert.rejects(()=>svc.submit(r.id,r.revision,driver),/products/);await assert.rejects(()=>svc.save(r.id,{kind:'Returned',reason:'Refused',lines:[{id:f.order+'-L',quantity:11,reason:'Refused'}]},r.revision,driver),/quantity/);const saved=await svc.save(r.id,{kind:'Returned',reason:'Wrong pack',lines:[{id:f.order+'-L',quantity:3,reason:'Wrong pack'}]},r.revision,driver);assert.equal((await svc.get(r.id,driver)).report_json.lines[0].quantity,3);assert.equal((await pool.query('SELECT total_amount FROM sales_orders WHERE id=$1',[f.order+'-L'])).rows[0].total_amount,200);assert.equal((await pool.query('SELECT count(*)::int AS n FROM inventory_lots')).rows[0].n,0);await assert.rejects(()=>svc.save(r.id,saved.report_json,r.revision,driver),/changed/);});
  await t.test('confirmation is idempotent and only seller can decide; corrections reopen editing',async()=>{const f=await trip();const r=await svc.open(f.id,f.order,'Shop closed',driver);const submitted=await svc.submit(r.id,r.revision,driver);assert.equal((await svc.submit(r.id,r.revision,driver)).revision,submitted.revision);await assert.rejects(()=>svc.save(r.id,r.report_json,submitted.revision,driver),/locked/);const input={decision:'Correction',note:'Please check with the customer',revision:submitted.revision};await assert.rejects(()=>svc.decide(r.id,input,driver),/seller/);await assert.rejects(()=>svc.decide(r.id,input,{...sales,id:99}),/seller/);const correction=await svc.decide(r.id,input,sales);assert.equal(correction.status,'Correction Requested');const changed=await svc.save(r.id,{...r.report_json,reason:'Customer confirms shop closed today'},correction.revision,driver);assert.equal(changed.report_json.reason,'Customer confirms shop closed today');await assert.rejects(()=>svc.submit(r.id,submitted.revision,driver),/changed/);});
  await t.test('exception stop cannot be completed, removed or reassigned while other stops can progress',async()=>{const f=await trip();await svc.open(f.id,f.order,'Shop closed',driver);const task=(await pool.query('SELECT * FROM delivery_tasks WHERE id=$1',[f.id])).rows[0];const payload={status:'Handed Over',assignedTo:'driver',routeStops:task.route_json};await assert.rejects(()=>assertDeliveryExceptionUpdate(pool as any,task,{...payload,status:'Delivered'}),/exceptions/);await assert.rejects(()=>assertDeliveryExceptionUpdate(pool as any,task,{...payload,routeStops:[]}),/exception/);await assert.rejects(()=>assertDeliveryExceptionUpdate(pool as any,task,{...payload,assignedTo:'someone'}),/exceptions/);await assertDeliveryExceptionUpdate(pool as any,task,{...payload,routeStops:task.route_json.map((s:any)=>s.orderId==='OTHER'?{...s,delivered:true}:s)});});
  await t.test('seller retry requires a future date; authorized return keeps custody and stock unchanged',async()=>{const f=await trip();let r=await svc.open(f.id,f.order,'Shop closed',driver);r=await svc.submit(r.id,r.revision,driver);await assert.rejects(()=>svc.decide(r.id,{decision:'Retry',note:'Visit later',revision:r.revision,dueAt:'2000-01-01'},sales),/future/);const retry=await svc.decide(r.id,{decision:'Retry',note:'Visit tomorrow',revision:r.revision,dueAt:new Date(Date.now()+86400000).toISOString()},sales);assert.equal(retry.status,'Retry Scheduled');const second=await svc.open(f.id,f.order,'Shop closed',driver);assert.notEqual(second.id,r.id);const sent=await svc.submit(second.id,second.revision,driver);const approved=await svc.decide(second.id,{decision:'Return',note:'Bring all goods back',revision:sent.revision},sales);assert.equal(approved.status,'Return Authorized');assert.equal(approved.agent_username,'driver');assert.equal((await pool.query('SELECT count(*)::int AS n FROM inventory_lots')).rows[0].n,0);});
  await t.test('old unresolved reports stay visible, unauthorized roles are denied, failed alerts retry',async()=>{const f=await trip();const r=await svc.open(f.id,f.order,'Shop closed',driver);await svc.submit(r.id,r.revision,driver);await pool.query("UPDATE delivery_exceptions SET created_at=NOW()-INTERVAL '100 days' WHERE id=$1",[r.id]);await pool.query("UPDATE delivery_exception_notifications SET status='Failed' WHERE case_id=$1",[r.id]);assert.ok((await svc.list(sales)).cases.some(c=>c.id===r.id&&c.failed_notifications>0));assert.equal((await svc.list({...driver,username:'other'})).cases.length,0);await assert.rejects(()=>svc.list({...sales,role:'Purchaser',roles:['Purchaser']}),/access/);await svc.retryNotifications(r.id,sales);assert.equal((await svc.get(r.id,sales)).failed_notifications,0);});
  await t.test('warehouse register excludes non-WhatsApp orders and other warehouse scopes',async()=>{
   const f=await trip();const r=await svc.open(f.id,f.order,'Shop closed',driver);const warehouse={id:3,username:'warehouse',fullName:'Warehouse',role:'Warehouse Manager',roles:['Warehouse Manager'],warehouseIds:['WH']};assert.equal((await svc.list(warehouse)).cases.length,0);
   await pool.query("UPDATE delivery_exceptions SET original_json=jsonb_set(original_json,'{0,note}','\"WhatsApp confirmed order WAD-TEST\"') WHERE id=$1",[r.id]);assert.ok((await svc.list(warehouse)).cases.some(c=>c.id===r.id));assert.equal((await svc.list({...warehouse,warehouseIds:['OTHER']})).cases.length,0);
  });
  await t.test('WhatsApp product selection, quantity entry, edit, submit and seller confirmation share persisted reports',async()=>{
   const f=await trip();const source=ts.createSourceFile('integration.ts',fs.readFileSync(path.join(root,'apps/api/src/whatsapp-integration.ts'),'utf8'),ts.ScriptTarget.Latest,true);const code=ts.transpileModule(source.statements.filter(s=>ts.isFunctionDeclaration(s)&&['handleDeliveryExceptionMessage','sendDeliveryExceptionCard'].includes(s.name?.text||'')).map(s=>s.getText(source)).join('\n'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}}).outputText;
   const messages:any[]=[];const dependencies={deliveryExceptionService:svc,executeDatabaseQuery:deps.query,isWhatsAppAdminUser:()=>false,text:(v:any)=>String(v??''),compact:(v:string,n:number)=>v.slice(0,n),getSnapshot:async()=>({deliveryTasks:[{id:f.id,assignedTo:'driver',routeStops:f.stops}]}),deliveryTaskAllowed:()=>true,sendText:async(_p:any,body:any)=>messages.push({body}),sendButtons:async(_p:any,body:any,buttons:any)=>messages.push({body,buttons}),sendGraphMessage:async(_p:any,body:any)=>messages.push({body}),processDeliveryExceptions:async()=>{}};
   const handle=new Function(...Object.keys(dependencies),code+';return handleDeliveryExceptionMessage;')(...Object.values(dependencies));const click=(id:string,actor=driver)=>handle({interactive:{button_reply:{id}}},'919999999999',actor);const say=(body:string,actor=driver)=>handle({text:{body}},'919999999999',actor);
   await click(`wa-ex:new:${f.id}:0:returned`);let r=(await svc.list(driver)).cases.find(c=>c.task_id===f.id);await click(`wa-ex:products:${r.id}:0`);await click(`wa-ex:product:${r.id}:${f.order}-L`);await say('3 | Packaging damaged');r=await svc.get(r.id,driver);assert.equal(r.report_json.lines[0].quantity,3);await click(`wa-ex:submit:${r.id}:${r.revision}`);r=await svc.get(r.id,sales);assert.equal(r.status,'Awaiting Seller');await click(`wa-ex:decision:${r.id}:${r.revision}:Return`,sales);await say('Return listed goods for warehouse inspection',sales);assert.equal((await svc.get(r.id,sales)).status,'Awaiting Seller');await click(`wa-ex:decide-confirm:${r.id}:${r.revision}`,sales);assert.equal((await svc.get(r.id,sales)).status,'Return Authorized');assert.ok(messages.some(m=>m.buttons?.some((b:any)=>b.title==='Confirm and send')));
  });
 }finally{await pool.end();await setup.query(`DROP SCHEMA ${schema} CASCADE`);await setup.end();}
});
