import assert from 'node:assert/strict';
import test from 'node:test';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import pg from 'pg';
import dotenv from 'dotenv';
import {createWhatsAppOutbox,enqueueWhatsApp} from '../src/whatsapp-outbox.js';
import {createOrderClosureService} from '../src/whatsapp-order-closure.js';
import {createShortageService} from '../src/whatsapp-shortages.js';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../..');
test('durable message failure and final order closure on isolated PostgreSQL',{skip:process.env.SHORTAGE_TEST_LOCAL!=='1'},async t=>{
 const env=dotenv.parse(fs.readFileSync(path.join(root,'.env')));const config={host:'127.0.0.1',port:5432,user:env.POSTGRES_USER||'aapoorti_app',password:env.POSTGRES_PASSWORD||'aapoorti123',database:env.POSTGRES_DB||'aapoorti_b2b'};
 const setup=new pg.Client(config);await setup.connect();const schema=`closure_test_${Date.now()}`;assert.match(schema,/^closure_test_\d+$/);await setup.query(`CREATE SCHEMA ${schema}`);const pool=new pg.Pool({...config,options:`-c search_path=${schema}`});
 const deps={query:(sql:string,args?:unknown[])=>pool.query(sql,args),transaction:async<T>(run:(db:pg.PoolClient)=>Promise<T>)=>{const c=await pool.connect();try{await c.query('BEGIN');const r=await run(c);await c.query('COMMIT');return r;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}};
 const service=createShortageService(deps);const closure=createOrderClosureService(deps);let failing=true;let sent=0;const transport=async(row:any)=>{if(failing)throw Error('Meta unavailable');return {messageId:`META-${++sent}-${row.id}`};};const outbox=createWhatsAppOutbox(deps,transport);
 const actor={id:1,fullName:'Sales',role:'Sales',roles:['Sales']};let n=0;
 async function draft(qty=10){const id=`WAD-CLOSE-${++n}`;await pool.query("INSERT INTO whatsapp_order_drafts(id,counterparty_id,phone_e164,salesman_id,warehouse_id,source,status) VALUES($1,'SHOP','919999999999',1,'WH','Retailer cart','Awaiting Retailer')",[id]);await pool.query("INSERT INTO whatsapp_order_draft_lines(id,draft_id,product_sku,requested_quantity,approved_quantity,rate) VALUES($1,$2,'SOAP',$3,$3,20)",[id+'-L',id,qty]);return id;}
 async function paidDelivery(id:string){const cart=await service.confirm(id);await pool.query("UPDATE sales_orders SET status='Delivered' WHERE cart_id=$1",[cart]);const total=Number((await pool.query('SELECT goods_value FROM ledger_entries WHERE linked_order_id=$1',[cart])).rows[0].goods_value);await pool.query("INSERT INTO payments(id,side,linked_order_id,amount,mode,reference_number,verification_status,created_by) VALUES($1,'Sales',$2,$3,'Cash',$1,'Verified','Test')",['PAY-'+id,cart,total]);await pool.query("UPDATE ledger_entries SET paid_amount=goods_value,pending_amount=0,status='Settled' WHERE linked_order_id=$1",[cart]);await pool.query("UPDATE whatsapp_outbox SET status='Sent' WHERE related_entity_id=$1",[id]);return cart;}
 try{
  await pool.query(fs.readFileSync(path.join(root,'postgres/init/001-schema.sql'),'utf8'));
  await pool.query(`INSERT INTO users(id,username,full_name,role,password) VALUES(1,'sales','Sales','Sales','unused');INSERT INTO counterparties(id,type,name,created_by) VALUES('SHOP','Shop','Test retailer','Test');INSERT INTO whatsapp_retailers(counterparty_id,phone_e164,salesman_id,default_warehouse_id,created_by) VALUES('SHOP','919999999999',1,'WH','Test');INSERT INTO products(sku,name,category,unit,default_weight_kg,tolerance_kg,tolerance_percent,allowed_warehouse_ids_json,slabs_json,created_by) VALUES('SOAP','Soap','Test','Piece',1,0,0,'["WH"]','[]','Test');INSERT INTO inventory_lots(lot_id,source_order_id,source_type,warehouse_id,product_sku,quantity_available,quantity_reserved,quantity_blocked,status) VALUES('LOT','TEST','Test','WH','SOAP',1000,0,0,'Available');`);
  await t.test('normal confirmation commits one SO and one acknowledgement despite concurrent confirmation and send failure',async()=>{
   const id=await draft();const [a,b]=await Promise.all([service.confirm(id),service.confirm(id)]);assert.equal(a,b);assert.equal((await pool.query('SELECT count(*)::int AS n FROM sales_orders WHERE cart_id=$1',[a])).rows[0].n,1);
   await outbox.dispatch(`${id}:order-confirmed`);assert.equal((await pool.query('SELECT status FROM whatsapp_order_drafts WHERE id=$1',[id])).rows[0].status,'Order Created');assert.equal((await pool.query('SELECT status FROM whatsapp_outbox WHERE id=$1',[`${id}:order-confirmed`])).rows[0].status,'Pending');assert.equal(await service.confirm(id),a);
   const restored=createWhatsAppOutbox(deps,transport);failing=false;await pool.query('UPDATE whatsapp_outbox SET available_at=NOW() WHERE id=$1',[`${id}:order-confirmed`]);await Promise.all([restored.dispatch(`${id}:order-confirmed`),restored.dispatch(`${id}:order-confirmed`)]);assert.equal(sent,1);await deps.transaction(db=>enqueueWhatsApp(db,'919999999999',{type:'text',text:{body:'Duplicate enqueue'}},'Draft',id,`${id}:order-confirmed`));assert.equal((await pool.query('SELECT count(*)::int AS n FROM sales_orders WHERE cart_id=$1',[a])).rows[0].n,1);
   const result=await closure.reconcile(id);assert.equal(result.complete,false);assert.ok(result.reasons.includes('Delivery pending'));await assert.rejects(()=>closure.assertComplete(id),/cannot be completed/);
  });
  await t.test('SO creation rolls back every line and ledger if a later product is unavailable',async()=>{const id=await draft();await pool.query("INSERT INTO products(sku,name,category,unit,default_weight_kg,tolerance_kg,tolerance_percent,allowed_warehouse_ids_json,slabs_json,created_by) VALUES('ZZ-NONE','Unavailable','Test','Piece',1,0,0,'[\"WH\"]','[]','Test')");await pool.query("INSERT INTO whatsapp_order_draft_lines(id,draft_id,product_sku,requested_quantity,approved_quantity,rate) VALUES($1,$2,'ZZ-NONE',1,1,20)",[id+'-X',id]);await assert.rejects(()=>service.confirm(id),/Stock/);assert.equal((await pool.query('SELECT count(*)::int AS n FROM sales_orders WHERE note=$1',[`WhatsApp confirmed order ${id}`])).rows[0].n,0);assert.equal((await pool.query('SELECT count(*)::int AS n FROM whatsapp_outbox WHERE related_entity_id=$1',[id])).rows[0].n,0);});
  await t.test('exhausted retries show failure-only manual notes; a note never resolves the message, and staff scope is enforced',async()=>{
   failing=true;const result=await outbox.send('919999999999',{type:'text',text:{body:'Delivery update'}},'Draft','FAILED-DRAFT');const id=result.messageId;assert.equal(result.queued,true);
   for(let i=0;i<4;i++){await pool.query('UPDATE whatsapp_outbox SET available_at=NOW() WHERE id=$1',[id]);await outbox.dispatch(id);}let row=(await pool.query('SELECT * FROM whatsapp_outbox WHERE id=$1',[id])).rows[0];assert.equal(row.status,'Failed');assert.equal(row.attempts,5);
   await assert.rejects(()=>outbox.act(id,'note','Later',{...actor,id:2}),/another staff/);await outbox.act(id,'note','Call retailer tomorrow; assigned to Sales',actor);assert.equal((await pool.query('SELECT status FROM whatsapp_outbox WHERE id=$1',[id])).rows[0].status,'Failed');assert.ok((await outbox.list(actor)).items.some(r=>r.id===id));
   await outbox.act(id,'resolve','Spoke to retailer by phone; update confirmed',actor);assert.ok(!(await outbox.list(actor)).items.some(r=>r.id===id));await assert.rejects(()=>outbox.act(id,'retry','',actor),/only available/);
  });
  await t.test('paid and delivered closes only after verified payment, and late Meta failure reopens until manual communication',async()=>{
   const id=await draft();const cart=await paidDelivery(id);await pool.query("UPDATE payments SET verification_status='Submitted' WHERE linked_order_id=$1",[cart]);assert.ok((await closure.reconcile(id)).reasons.includes('Payment verification pending'));await pool.query("UPDATE payments SET verification_status='Verified' WHERE linked_order_id=$1",[cart]);assert.equal((await closure.reconcile(id)).complete,true);
   failing=false;const result=await outbox.send('919999999999',{type:'text',text:{body:'Delivery completed'}},'Draft',id);await outbox.receipt(result.messageId,'failed','Meta delivery rejected');assert.equal((await closure.reconcile(id)).complete,false);assert.equal((await pool.query('SELECT status FROM whatsapp_order_drafts WHERE id=$1',[id])).rows[0].status,'Order Created');const o=(await pool.query('SELECT id FROM whatsapp_outbox WHERE wa_message_id=$1',[result.messageId])).rows[0];await outbox.act(o.id,'note','Follow up later',actor);assert.equal((await closure.reconcile(id)).complete,false);await outbox.act(o.id,'resolve','Customer confirmed update by phone',actor);assert.equal((await closure.reconcile(id)).complete,true);
  });
  await t.test('24 delivered cannot complete the original order while 36 remain pending or while the balance delivery is unpaid',async()=>{
   const id=await draft(24);await paidDelivery(id);const caseId='SHORT-'+id;await pool.query("INSERT INTO whatsapp_shortage_cases(id,draft_id,counterparty_id,salesman_id,warehouse_id,retailer_choice,purchase_status) VALUES($1,$2,'SHOP',1,'WH','Split','Not Required')",[caseId,id]);await pool.query("INSERT INTO whatsapp_shortage_lines(case_id,draft_line_id,product_sku,requested_quantity,available_quantity,pending_quantity) VALUES($1,$2,'SOAP',60,24,36)",[caseId,id+'-L']);assert.ok((await closure.reconcile(id)).reasons.includes('Remaining demand pending'));
   const balance=await draft(36);await pool.query('INSERT INTO whatsapp_shortage_portions(draft_id,case_id) VALUES($1,$2)',[balance,caseId]);await pool.query('UPDATE whatsapp_shortage_lines SET released_quantity=36 WHERE case_id=$1',[caseId]);const balanceCart=await service.confirm(balance);await pool.query("UPDATE whatsapp_shortage_notifications SET status='Sent' WHERE case_id=$1",[caseId]);assert.ok((await closure.reconcile(id)).reasons.includes('Delivery pending'));await pool.query("UPDATE sales_orders SET status='Delivered' WHERE cart_id=$1",[balanceCart]);assert.ok((await closure.reconcile(id)).reasons.includes('Collection pending'));await paidDelivery(balance);const result=await closure.reconcile(balance);assert.equal(result.complete,true);assert.equal((await pool.query('SELECT count(*)::int AS n FROM whatsapp_order_drafts WHERE id=ANY($1::text[]) AND status=\'Completed\'',[result.ids])).rows[0].n,2);
  });
  await t.test('warehouse custody and prepaid excess keep closure open after delivery',async()=>{
   const id=await draft();const cart=await paidDelivery(id);await pool.query("INSERT INTO delivery_tasks(id,side,linked_order_id,mode,source_location,destination_location,assigned_to,status) VALUES($1,'Sales',$2,'Delivery','WH','SHOP','agent','Handed Over')",['TASK-'+id,cart]);await pool.query("INSERT INTO delivery_exceptions(id,task_id,order_id,shop_id,warehouse_id,agent_username,original_json,report_json,status) VALUES($1,$2,$3,'SHOP','WH','agent','[]','{}','Awaiting Warehouse')",['DEX-'+id,'TASK-'+id,cart]);assert.ok((await closure.reconcile(id)).reasons.includes('Return receipt or return financial resolution pending'));await pool.query("UPDATE delivery_exceptions SET status='Closed' WHERE id=$1",['DEX-'+id]);await pool.query('UPDATE payments SET amount=amount+10 WHERE linked_order_id=$1',[cart]);assert.ok((await closure.reconcile(id)).reasons.includes('Credit or refund resolution pending'));
  });
  await t.test('packing balance links keep the original open, and a missing ledger cannot pass financial closure',async()=>{
   const id=await draft();const cart=await paidDelivery(id);const balance=await draft(2);await pool.query("INSERT INTO whatsapp_packing_reviews(id,cart_id,shop_id,salesman_id,warehouse_id,status,original_json,balance_draft_id) VALUES($1,$2,'SHOP',1,'WH','Finalized','[]',$3)",['PACK-'+id,cart,balance]);assert.ok((await closure.reconcile(id)).reasons.includes('Remaining quantity or retailer confirmation pending'));await pool.query("UPDATE whatsapp_order_drafts SET status='Denied' WHERE id=$1",[balance]);assert.equal((await closure.reconcile(id)).complete,true);await pool.query('DELETE FROM ledger_entries WHERE linked_order_id=$1',[cart]);assert.ok((await closure.reconcile(id)).reasons.includes('Financial reconciliation pending'));
  });
  await t.test('fresh queued messages are hidden, abandoned leases recover, and out-of-order sent receipts cannot erase a delivery failure',async()=>{
   const id=await deps.transaction(db=>enqueueWhatsApp(db,'919999999999',{type:'text',text:{body:'Recoverable update'}},'Draft','RECOVERY'));assert.ok(!(await outbox.list(actor)).items.some(o=>o.id===id));await pool.query("UPDATE whatsapp_outbox SET status='Sending',available_at=NOW()-INTERVAL '10 minutes' WHERE id=$1",[id]);failing=false;await Promise.all([outbox.dispatch(id),outbox.dispatch(id)]);const row=(await pool.query('SELECT * FROM whatsapp_outbox WHERE id=$1',[id])).rows[0];assert.equal(row.attempts,1);assert.equal(row.status,'Sent');await outbox.receipt(row.wa_message_id,'failed','Rejected delivery');await outbox.receipt(row.wa_message_id,'sent','');assert.equal((await pool.query('SELECT status FROM whatsapp_outbox WHERE id=$1',[id])).rows[0].status,'Pending');await outbox.receipt(row.wa_message_id,'delivered','');await outbox.receipt(row.wa_message_id,'failed','Late failure');assert.equal((await pool.query('SELECT status FROM whatsapp_outbox WHERE id=$1',[id])).rows[0].status,'Delivered');
  });
  await t.test('a failed-delivery webhook arriving before the HTTP response is retained and retried',async()=>{
   const id=await deps.transaction(db=>enqueueWhatsApp(db,'919999999999',{type:'text',text:{body:'Early receipt'}},'Draft','EARLY-RECEIPT'));
   const early=createWhatsAppOutbox(deps,async row=>{await outbox.receipt('EARLY-'+row.id,'failed','Delivery failed before response persisted');return {messageId:'EARLY-'+row.id};});await early.dispatch(id);const row=(await pool.query('SELECT * FROM whatsapp_outbox WHERE id=$1',[id])).rows[0];assert.equal(row.status,'Pending');assert.match(row.last_error,/before response/);
  });
  await t.test('queued marketing retries honor a later opt-out',async()=>{
   failing=true;const message=await outbox.send('919999999999',{type:'text',text:{body:'Offer campaign'}},'Broadcast','CAMPAIGN');await pool.query("UPDATE whatsapp_retailers SET marketing_opt_in=FALSE WHERE counterparty_id='SHOP'");await pool.query('UPDATE whatsapp_outbox SET available_at=NOW() WHERE id=$1',[message.messageId]);failing=false;await outbox.dispatch(message.messageId);assert.equal((await pool.query('SELECT status FROM whatsapp_outbox WHERE id=$1',[message.messageId])).rows[0].status,'Superseded');
  });
  await t.test('obsolete confirmation buttons are superseded rather than resent after SO creation',async()=>{
   const id=await draft();const key=await deps.transaction(db=>enqueueWhatsApp(db,'919999999999',{type:'interactive',interactive:{action:{buttons:[{reply:{id:`wa-confirm:${id}`}}]}}},'Draft',id));failing=true;await outbox.dispatch(key);await service.confirm(id);await outbox.act(key,'retry','',actor);failing=false;await outbox.dispatch(key);assert.equal((await pool.query('SELECT status FROM whatsapp_outbox WHERE id=$1',[key])).rows[0].status,'Superseded');
  });
 }finally{await pool.end();await setup.query(`DROP SCHEMA ${schema} CASCADE`);await setup.end();}
});
