import {useCallback,useEffect,useRef,useState} from 'react';
import axios from 'axios';
import {api,formatDateTimeIst} from '../../app/shared';
import {Panel} from '../../components/ui';
type Failure={id:string;recipient_name:string;phone_e164:string;status:string;attempts:number;last_error:string;manual_note:string;related_entity_type:string;related_entity_id:string;available_at:string;payload_json:{text?:{body?:string};interactive?:{body?:{text?:string}}}};
function FailureCard({item,busy,act}:{item:Failure;busy:boolean;act:(id:string,action:string,note:string)=>Promise<void>}){
 const [note,setNote]=useState(item.manual_note||'');const [contacted,setContacted]=useState(false);
 return <article className="panel"><h3>{item.recipient_name}</h3><p style={{overflowWrap:'anywhere'}}>{item.related_entity_type} / {item.related_entity_id} / {item.phone_e164}</p><p role="alert">WhatsApp delivery failed. Record a manual follow-up note and retry later.</p><p>{item.last_error}</p><p>{item.status} / Attempts: {item.attempts}{item.status==='Pending'?` / Next retry: ${formatDateTimeIst(item.available_at)}`:''}</p><details><summary>Message details</summary><p style={{overflowWrap:'anywhere'}}>{item.payload_json.text?.body||item.payload_json.interactive?.body?.text||JSON.stringify(item.payload_json)}</p></details><div className="form-grid"><label className="wide-field">Manual follow-up note<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Record the problem, responsible person and next action."/></label><div className="payment-card-actions wide-field"><button className="ghost-button" disabled={busy||!note.trim()||item.status==='Sending'} onClick={()=>void act(item.id,'note',note)}>Save note for later</button><button className="primary-button" disabled={busy||item.status==='Sending'} onClick={()=>void act(item.id,'retry',note)}>Retry message</button></div><label className="wide-field"><input type="checkbox" checked={contacted} onChange={e=>setContacted(e.target.checked)}/> I communicated this update through another channel and recorded the details.</label><button className="ghost-button" disabled={busy||!contacted||!note.trim()||item.status==='Sending'} onClick={()=>void act(item.id,'resolve',note)}>Confirm manual communication</button></div></article>;
}
export function MessageFailures({sessionToken}:{sessionToken:string}){
 const [items,setItems]=useState<Failure[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const active=useRef(false);const seq=useRef(0);
 const failure=(e:unknown)=>axios.isAxiosError(e)?String(e.response?.data?.message||e.message):e instanceof Error?e.message:'Unable to update failed messages.';
 const refresh=useCallback(async()=>{if(active.current)return;const n=++seq.current;try{const {data}=await api.get<{items:Failure[]}>('/whatsapp/message-failures',{headers:{authorization:`Bearer ${sessionToken}`}});if(n===seq.current){setItems(data.items);setError('');}}catch(e){if(n===seq.current)setError(failure(e));}},[sessionToken]);
 useEffect(()=>{void refresh();const timer=setInterval(()=>void refresh(),10000);return()=>{clearInterval(timer);seq.current++;};},[refresh]);
 async function act(id:string,action:string,note:string){if(active.current)return;active.current=true;setBusy(true);seq.current++;try{const {data}=await api.post<{items:Failure[]}>(`/whatsapp/message-failures/${encodeURIComponent(id)}/${action}`,{note},{headers:{authorization:`Bearer ${sessionToken}`}});setItems(data.items);setError('');}catch(e){setError(failure(e));}finally{active.current=false;setBusy(false);}}
 if(!items.length&&!error)return null;
 return <Panel title="WhatsApp delivery failures" eyebrow="Retry / Manual follow-up">{error?<p role="alert">{error}</p>:null}<p>Only failed messages appear here. Saving a note keeps follow-up open; it does not mark the message delivered or the order completed.</p><div className="stacked-sections">{items.map(item=><FailureCard key={item.id} item={item} busy={busy} act={act}/>)}</div></Panel>;
}
