import {useCallback,useEffect,useState} from 'react';
import axios from 'axios';
import {api,formatDateTimeIst} from '../../app/shared';
import {Panel} from '../../components/ui';
type Case={case_key:string;kind:string;reference:string;status:string;assigned_owner_id:number;owner_name:string;deadline:string;action_required:string;overdue:boolean;created_at:string};
type Data={items:Case[];staff:{id:number;full_name:string}[]};
export function OpenCases({sessionToken}:{sessionToken:string}){
 const [data,setData]=useState<Data>({items:[],staff:[]});const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [filter,setFilter]=useState('');
 const fail=(e:unknown)=>setError(axios.isAxiosError(e)?String(e.response?.data?.message||e.message):String(e));
 const refresh=useCallback(async()=>{const r=await api.get<Data>('/whatsapp/open-cases',{headers:{authorization:`Bearer ${sessionToken}`}});setData(r.data);},[sessionToken]);
 useEffect(()=>{void refresh().catch(fail);},[refresh]);
 return <Panel title="All unresolved cases" eyebrow="WhatsApp Admin"><p>All ages are included. Assigning a follow-up keeps the case open until its underlying workflow is resolved.</p><div className="form-grid"><label>Find case<input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Order, status, owner or action"/></label><button className="ghost-button" disabled={busy} onClick={()=>void refresh().catch(fail)}>Refresh {data.items.length} open cases</button></div>{error?<p role="alert">{error}</p>:null}<div className="stacked-sections">{data.items.filter(c=>`${c.reference} ${c.kind} ${c.status} ${c.owner_name} ${c.action_required}`.toLowerCase().includes(filter.toLowerCase())).map(c=><article className="panel" key={c.case_key}><h3>{c.kind} · {c.status}</h3><p style={{overflowWrap:'anywhere'}}>{c.reference}</p><p>{c.owner_name||'Owner assignment required'} · {c.overdue?'Overdue':'Due'}: {formatDateTimeIst(c.deadline)}</p><p>{c.action_required}</p><small>Opened {formatDateTimeIst(c.created_at)}</small><details><summary>Assign next action</summary><form className="form-grid" onSubmit={async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));setBusy(true);setError('');try{const r=await api.post<Data>('/whatsapp/open-cases/assign',{caseKey:c.case_key,ownerId:Number(f.ownerId),dueAt:new Date(String(f.dueAt)).toISOString(),nextAction:f.nextAction},{headers:{authorization:`Bearer ${sessionToken}`}});setData(r.data);}catch(e){fail(e);}finally{setBusy(false);}}}><label>Owner<select name="ownerId" required defaultValue={c.assigned_owner_id||''}><option value="" disabled>Select owner</option>{data.staff.map(u=><option key={u.id} value={u.id}>{u.full_name}</option>)}</select></label><label>Deadline<input type="datetime-local" name="dueAt" required/></label><label>Next action<textarea name="nextAction" defaultValue={c.action_required} required/></label><button className="primary-button" disabled={busy}>Save assignment</button></form></details></article>)}</div>{!data.items.length?<p>No unresolved cases.</p>:null}</Panel>;
}
