import {useCallback,useEffect,useRef,useState} from 'react';
import type {FormEvent} from 'react';
import axios from 'axios';
import {api,formatDateTimeIst} from '../../app/shared';
import {Panel} from '../../components/ui';
type Staff={id:number;username:string;full_name:string;role:string;roles?:string[]};
type Credit={source_order_id:string;shop_id:string;amount:string;available_amount:string};
type Refund={id:string;source_order_id:string;shop_id:string;amount:string;status:string;version:number;note:string;payment_reference:string;proof:string;decision_note:string};
type Collection={order_id:string;shop_name:string;owner_id:number;owner_name:string;collector_username:string;amount_due:string;due_at:string;overdue:boolean;version:number;note:string};
type Data={shops:{id:string;name:string}[];credits:Credit[];refunds:Refund[];collections:Collection[];staff:Staff[]};
type Action=(path:string,body:object)=>Promise<boolean>;
const amount=(n:unknown)=>`Rs.${Number(n||0).toFixed(2)}`;
const localDate=(date:string)=>{const d=new Date(date);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
const fields=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();return Object.fromEntries(new FormData(e.currentTarget));};
function CreditCard({credit,name,busy,act}:{credit:Credit;name:string;busy:boolean;act:Action}){
 const requestKey=useRef(crypto.randomUUID());
 return <article className="panel"><h3>{name}</h3><p style={{overflowWrap:'anywhere'}}>{credit.source_order_id}</p><p>Ledger credit: <strong>{amount(credit.amount)}</strong> · Available: {amount(credit.available_amount)}</p><p>Available credit automatically offsets delivered unpaid bills first, then dispatched bills. Pending demand is billed on its later delivery.</p>
 {Number(credit.available_amount)>0?<details><summary>Retailer requested a refund</summary><form className="form-grid" onSubmit={async e=>{const form=e.currentTarget;const f=fields(e);if(await act('/refunds',{...f,amount:Number(f.amount),sourceOrderId:credit.source_order_id,requestKey:requestKey.current})){requestKey.current=crypto.randomUUID();form.reset();}}}><label>Refund amount<input name="amount" type="number" min="0.01" max={credit.available_amount} step="0.01" required/></label><label>Retailer request details<textarea name="note" required/></label><button className="primary-button" disabled={busy}>Reserve credit and request refund</button></form></details>:null}</article>;
}
function RefundCard({item,name,busy,act,seller,accounts}:{item:Refund;name:string;busy:boolean;act:Action;seller:boolean;accounts:boolean}){
 return <article className="panel"><h3>{name} · {amount(item.amount)}</h3><p style={{overflowWrap:'anywhere'}}>{item.id} / {item.source_order_id}</p><p><strong>{item.status}</strong> · {item.note}</p>{item.payment_reference?<p>Payment reference: {item.payment_reference}<br/>Evidence: {item.proof}</p>:null}{item.decision_note?<p>{item.decision_note}</p>:null}
 {!['Verified','Cancelled','Rejected'].includes(item.status)?<form className="form-grid" onSubmit={e=>{const f=fields(e);const action=String(f.action);void act(`/refunds/${encodeURIComponent(item.id)}/${action}`,{...f,version:item.version});}}>
 <label>Decision / verification note<textarea name="note" required/></label>
 {item.status==='Approved'&&accounts?<><label>Payment reference<input name="reference"/></label><label>Payment evidence reference or URL<input name="proof"/></label></>:null}
 <label>Action<select name="action" required defaultValue=""><option value="" disabled>Select action</option>{seller&&item.status==='Requested'?<><option value="approve">Approve refund</option><option value="reject">Reject with reason</option></>:null}{seller&&['Requested','Approved'].includes(item.status)?<option value="cancel">Cancel before payout</option>:null}{accounts&&item.status==='Approved'?<option value="pay">Record completed payout</option>:null}{accounts&&item.status==='Paid'?<option value="verify">Verify payment and close refund</option>:null}</select></label><button className="primary-button" disabled={busy}>Confirm refund action</button></form>:null}</article>;
}
function CollectionCard({item,staff,busy,act,canSchedule}:{item:Collection;staff:Staff[];busy:boolean;act:Action;canSchedule:boolean}){
 return <article className="panel"><h3>{item.shop_name} · {amount(item.amount_due)}</h3><p style={{overflowWrap:'anywhere'}}>{item.order_id}</p><p>{item.owner_name} · {item.overdue?'Overdue — Admin escalation':'Next follow-up'}: {formatDateTimeIst(item.due_at)}</p>{Number(item.amount_due)===0?<p>Receipt submitted. Verify the payment to close this follow-up; no further collection is due.</p>:null}{Number(item.amount_due)>0?<details><summary>Record collection</summary><form className="form-grid" onSubmit={e=>{const f=fields(e);void act(`/collections/${encodeURIComponent(item.order_id)}/pay`,{...f,amount:Number(f.amount)});}}><label>Amount received<input name="amount" type="number" min="0.01" step="0.01" max={item.amount_due} required/></label><label>Mode<select name="mode"><option>Cash</option><option>UPI</option><option>NEFT</option><option>RTGS</option><option>Cheque</option></select></label><label>Payment reference<input name="reference" required/></label><label>Payment evidence reference or URL<input name="proof"/></label><button className="primary-button" disabled={busy}>Submit receipt for verification</button></form></details>:null}{canSchedule?<form className="form-grid" onSubmit={e=>{const f=fields(e);void act(`/collections/${encodeURIComponent(item.order_id)}`,{...f,version:item.version,ownerId:Number(f.ownerId),dueAt:new Date(String(f.dueAt)).toISOString()});}}>
 <label>Sales owner<select name="ownerId" defaultValue={item.owner_id} required>{staff.filter(u=>u.role==='Sales'||u.roles?.includes('Sales')).map(u=><option key={u.id} value={u.id}>{u.full_name} ({u.role})</option>)}</select></label><label>Assigned collector<select name="collector" defaultValue={item.collector_username||''}><option value="">Sales will assign</option>{staff.filter(u=>[u.role,...(u.roles||[])].some(r=>['Collection Agent','Delivery','Out Delivery'].includes(r))).map(u=><option key={u.id} value={u.username}>{u.full_name} ({u.role})</option>)}</select></label><label>Next follow-up date<input name="dueAt" type="datetime-local" defaultValue={localDate(item.due_at)} required/></label><label>Next action / collection note<textarea name="note" defaultValue={item.note} required/></label><button className="primary-button" disabled={busy}>Save follow-up</button></form>:null}<p>Closure follows verified settlement. Collect only the outstanding delivered bill.</p></article>;
}
export function RetailerFinance({sessionToken,roles,admin=false}:{sessionToken:string;roles:string[];admin?:boolean}){
 const [data,setData]=useState<Data|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const inFlight=useRef(false);
 const errorText=(e:unknown)=>axios.isAxiosError(e)?String(e.response?.data?.message||e.message):e instanceof Error?e.message:'Unable to load retailer finances.';
 const refresh=useCallback(async()=>{const {data}=await api.get<Data>('/whatsapp/finance',{headers:{authorization:`Bearer ${sessionToken}`}});setData(data);},[sessionToken]);
 useEffect(()=>{let active=true;void api.get<Data>('/whatsapp/finance',{headers:{authorization:`Bearer ${sessionToken}`}}).then(r=>{if(active)setData(r.data);}).catch(e=>{if(active)setError(errorText(e));});return()=>{active=false;};},[sessionToken]);
 async function act(path:string,body:object){if(inFlight.current)return false;inFlight.current=true;setBusy(true);setError('');try{await api.post('/whatsapp/finance'+path,body,{headers:{authorization:`Bearer ${sessionToken}`}});await refresh();return true;}catch(e){setError(errorText(e));return false;}finally{inFlight.current=false;setBusy(false);}}
 const name=(shop:string)=>data?.shops.find(s=>s.id===shop)?.name||shop;
 return <Panel title="Retailer credit, collections and refunds" eyebrow="Financial follow-up"><button className="ghost-button" disabled={busy} onClick={()=>void refresh().catch(e=>setError(errorText(e)))}>Refresh balances</button>{error?<p role="alert">{error}</p>:null}{data?<>
 <details open={data.collections.length>0}><summary>Open collections ({data.collections.length})</summary><div className="stacked-sections">{data.collections.map(c=><CollectionCard key={`${c.order_id}:${c.version}`} item={c} staff={data.staff} busy={busy} act={act} canSchedule={admin||roles.some(r=>['Sales','Accounts'].includes(r))}/>)}</div></details>
 <details><summary>Available / reserved retailer credit ({data.credits.length})</summary><div className="stacked-sections">{data.credits.map(c=><CreditCard key={c.source_order_id} credit={c} name={name(c.shop_id)} busy={busy} act={act}/>)}</div></details>
 <details open={data.refunds.some(r=>!['Verified','Rejected','Cancelled'].includes(r.status))}><summary>Refund cases ({data.refunds.length})</summary><div className="stacked-sections">{data.refunds.map(r=><RefundCard key={`${r.id}:${r.version}`} item={r} name={name(r.shop_id)} busy={busy} act={act} seller={admin||roles.includes('Sales')} accounts={admin||roles.includes('Accounts')}/>)}</div></details>
 {!data.collections.length&&!data.credits.length&&!data.refunds.length?<p>No outstanding retailer finance cases.</p>:null}</>:<p>Loading balances…</p>}</Panel>;
}
